// Easter egg loading messages from famous video games
export const LOADING_MESSAGES = [
    "The cake is a lie...",
    "War. War never changes.",
    "Would you kindly wait a moment?",
    "It's dangerous to go alone!",
    "All your base are belong to us",
    "A man chooses, a slave obeys...",
    "Do a barrel roll!",
    "The princess is in another castle",
    "Stay awhile and listen!",
    "You must construct additional pylons",
    "Finish him!",
    "Had to be me. Someone else might have gotten it wrong.",
    "I used to be an adventurer like you...",
    "Remember, no Russian.",
    "Grove Street. Home.",
    "Praise the Sun! \\[T]/",
    "A hero need not speak...",
    "Wake up, Mr. Freeman.",
    "The right man in the wrong place...",
    "Kept you waiting, huh?",
    "Snake? Snake?! SNAAAAKE!",
    "It's time to kick ass and chew bubblegum...",
    "Get over here!",
    "Booker, are you afraid of God?",
    "No gods or kings. Only man.",
    "The numbers, Mason! What do they mean?",
    "Press F to pay respects",
    "I'm Commander Shepard, and this is my favorite store",
    "We'll bang, OK?",
    "I should go.",
    "Requiescat in pace",
    "Nothing is true, everything is permitted",
    "May the Force be with you... wait, wrong franchise",
    "I need a weapon.",
    "Finish the fight.",
    "Were it so easy...",
    "I am the monument to all your sins",
    "Protocol 3: Protect the Pilot",
    "Trust me.",
    "The truth is... the game was rigged from the start",
    "Patrolling the Mojave almost makes you wish for nuclear winter",
    "Another settlement needs your help!",
    "Hey! Listen!",
    "Hyah! Hyah! Hyah!",
    "You died",
    "Humanity restored",
    "Don't give up, skeleton!",
    "Try finger but hole",
    "Amazing chest ahead",
    "Hesitation is defeat",
    "A corpse should be left well alone",
    "Fear the old blood",
    "May you find your worth in the waking world",
    "Good hunter, you have come...",
    "Tonight, Gehrman joins the hunt",
    "Beasts all over the shop...",
    "We are born of the blood, made men by the blood",
    "Grant us eyes!",
    "Kos, or some say Kosm...",
    "The sweet blood, oh, it sings to me",
    "A hunter must hunt",
    "What a save!",
    "Calculated.",
    "Nice shot!",
    "Oof!",
    "Roblox death sound: OOF",
    "Steve has made the achievement [Getting Wood]",
    "Creeper? Aw man...",
    "It's high noon",
    "Heroes never die!",
    "Nerf this!",
    "Justice rains from above!",
    "Die! Die! Die!",
    "I've got you in my sights",
    "Cheers love, the cavalry's here!",
    "Experience tranquility",
    "Ryūjin no ken wo kūrae!",
    "Fire in the hole!",
    "The world could always use more heroes",
    "Winky face ;)",
    "GG EZ",
    "Rush B, no stop!",
    "Terrorists win",
    "Counter-Terrorists win",
    "Bomb has been planted",
    "Bomb has been defused",
    "Headshot!",
    "M-M-M-MONSTER KILL!",
    "Godlike!",
    "Rampage!",
    "First blood!",
    "Double kill!",
    "Triple kill!",
    "PENTAKILL!",
    "An ally has been slain",
    "You have slain an enemy",
    "Ace!",
    "Leeeeeroy Jenkins!",
    "Time's up, let's do this!",
];
